<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL);
include("dbconfig.php");
/*$host = 'localhost';
$username = 'ermsuser';
$password = 'password';
$database = 'ERMS';
$dbport = 3306;
// Create connection
$con = new mysqli($host, $username, $password, $database, $dbport);
#$con = mysqli("localhost", "gtuser", "gtuser123",3303);
if (!$con) {
	die("Failed to connect to database");
}
#mysqli_select_db("gtonline_complete") or die( "Unable to select database"); */

$errorMsg = "";

session_start();
if (!isset($_SESSION['username'])) {
    header('Location: login.php');
    exit();
}

/* if Save button was clicked, input information is saved into incident table */

if(isset($_POST['Save']))


{

    /* validate form */

    if (is_date($_POST['Date'])) {

        $IncidentDate = $_POST['Date'];

    }

    else {

        $IncidentDate = '';

    }


    $Description = mysqli_real_escape_string($con,$_POST['Description']);
    $LatI = mysqli_real_escape_string($con,$_POST['Lat']);
    $LongI = mysqli_real_escape_string($con,$_POST['Lng']);


    /* Insert user input form information into Incident table, incidentID is generated by randnumber  */
    /*for ($i=0;$i<1000000;$i++) {

        $IncidentID=mt_rand (1,1000000);

        $query = "INSERT INTO incident (IncidentID, IncidentDate,Description,LatI,LongI,OwnerName) " .

            "VALUES('$IncidentID','$IncidentDate','$Description','$LatI','$LongI','{$_SESSION['username']}')";

        if (!mysqlii_query($con,$query)) {

            print '<p class="error">Error: Failed to add incident. ' . mysqli_error($con) . '</p>';

        }


    } */

    /* Retrive Incident in order to display incident information in the incident form  */
    $sql="SELECT IncidentID, IncidentDate, Description, LatI, LongI, OwnerName FROM Incident;";

    $result=$con->query($sql);

    if (!$result) {

        print "<p class='error'>Error: " . mysqli_error($con) . "</p>";

        exit();

    }

    $row = mysqli_fetch_array($result,MYSQLI_ASSOC);

    if (!$row) {

        print "<p>Error: No data returned from database.</p>";

        exit();

    }



    /* if Cancel button was clicked, input information is cancelled from  incident table in erms database */

    if(isset($_POST['Cancel'])) {

        $sql = "DELETE FROM incident " .

            "WHERE IncidentID = '$IncidentID' " ;


        if (!mysqli_query($con,$sql)) {

            print '<p class="error">Error: Failed to delete incident. ' . mysqli_error($con) . '</p>';

        }

    }



    function is_date( $str ) {

        $stamp = strtotime( $str );

        if (!is_numeric($stamp)) {

            return false;

        }

        $month = date( 'm', $stamp );

        $day   = date( 'd', $stamp );

        $year  = date( 'Y', $stamp );



        if (checkdate($month, $day, $year)) {

            return true;

        }

        return false;

    }







    ?>



    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

    <html xmlns="http://www.w3.org/1999/xhtml">

    <head>

        <title>ERMS Add　Emergency Incident</title>

        <link rel="stylesheet" type="text/css" href="style.css" />

    </head>



    <body>



    <div id="main_container">



        <div id="header">

        </div>


        <div class="menu">


        </div>



        <div class="center_content">



            <div class="center_left">
                <div class="title">New Incident Info</div>

                <td class="item_label">IncidentID</td> <?php print $row['IncidentID'] ; ?></div>



					<div class="features">   

	

							<form name="incidentform" action="add_incident.php" method="post">

							<table width="80%">

				
									<td class="item_label">Date</td>

									<td>

										<input type="text" name="Date" value="<?php if ($row['IncidentDate']) { print $row['IncidentDate']; } ?>" />										

									</td>

								</tr>

								<tr>

									<td class="item_label">Description</td>

									<td>

										<input type="text" name="Description" value="<?php if ($row['Description']) { print $row['Description']; } ?>" />	

									</td>

								</tr>
                                
								<tr>

									<td class="item_label">Location</td>

									<td>

										<input type="text" name="Lat" value="<?php if ($row['LatI']) { print $row['LatI']; } ?>" />	
										<input type="text" name="Lng" value="<?php if ($row['LongI']) { print $row['LongI']; } ?>" />	

									</td>

								</tr>
								<input type="submit" name="Save" value="Save"/>
								<input type="submit" name="Cancel" value="Cancel"/>

	

							</form>

						

						</div>

			

					 </div> 

					

				</div> 

				

				<div class="clear"></div> 

			

			</div>    



		

			<div id="footer">                                              

				<div class="right_footer"><a href="http://csstemplatesmarket.com"  target="_blank">http://csstemplatesmarket.com</a></div>       

			</div>

			

		 

		</div>



	</body>

</html>